#####################################################################
#
# fscheck.c is the name of the source code;
#
# Type "make" or "make fscheck" to compile your code
# 
# Type "make clean" to remove the executable (and any object files)
#
#####################################################################

CC=gcc
CFLAGS=-Wall -g

fscheck: fscheck.c
	$(CC) -o fscheck $(CFLAGS) fscheck.c

clean:
	$(RM) fscheck
